- algonaut_client/tests/test_trasactions.rs
- algonaut_core/src/lib.rs
- examples/sign_offline.rs
- examples/sign_submit_transaction.rs
- examples/sign_submit_transaction_sandnet.rs
> Implement FromStr/ToString for Address

- algonaut_client/src/algod/v1/mod.rs
- algonaut_client/src/kmd/v1/mod.rs
- algonaut_client/tests/test_trasactions.rs
- algonaut_core/Cargo.toml
- algonaut_core/src/lib.rs
- algonaut_transaction/src/account.rs
- algonaut_transaction/src/api_transaction.rs
- algonaut_transaction/src/auction.rs
- algonaut_transaction/src/builder.rs
- algonaut_transaction/src/error.rs
- algonaut_transaction/src/lib.rs
- algonaut_transaction/src/transaction.rs
- algonaut_transaction/src/tx_group.rs
- examples/sign_offline.rs
Working so far, but requires https://github.com/manuelmauro/algonaut/issues/29 fix 
Initially I thought that this problem doesn't affect kmd signing, but weirdly it does when using groups.
> Support transaction groups

- algonaut_client/src/algod/v1/mod.rs
- algonaut_client/src/kmd/v1/mod.rs
- algonaut_client/tests/test_trasactions.rs
- algonaut_core/Cargo.toml
- algonaut_core/src/lib.rs
- algonaut_transaction/src/account.rs
- algonaut_transaction/src/api_transaction.rs
- algonaut_transaction/src/auction.rs
- algonaut_transaction/src/builder.rs
- algonaut_transaction/src/error.rs
- algonaut_transaction/src/lib.rs
- algonaut_transaction/src/transaction.rs
- algonaut_transaction/src/tx_group.rs
- examples/sign_offline.rs
> Use direct signing in transaction tests

- algonaut_core/src/lib.rs
- algonaut_crypto/src/lib.rs
https://github.com/manuelmauro/algonaut/pull/37 with updated target branch.
> Improve debug representation of transactions

- Cargo.toml
- algonaut_client/src/algod/v2/mod.rs
- src/algod/v1/mod.rs
- src/algod/v2/mod.rs
- tests/test_algod_v1.rs
- tests/test_algod_v2.rs
- tests/test_trasactions.rs
Making use of the new abstraction layer.
> Add convenience to send transactions and use Address

- Cargo.toml
- algonaut_client/Cargo.toml
- algonaut_client/src/algod/v1/mod.rs
- algonaut_client/src/algod/v2/mod.rs
- algonaut_client/src/error.rs
- algonaut_client/src/extensions/reqwest.rs
- algonaut_client/src/indexer/v2/mod.rs
- algonaut_client/src/kmd/v1/mod.rs
- algonaut_client/src/token.rs
- algonaut_crypto/src/error.rs
- algonaut_crypto/src/mnemonic/mod.rs
- algonaut_transaction/src/account.rs
- algonaut_transaction/src/api_model.rs
- algonaut_transaction/src/error.rs
- algonaut_transaction/src/transaction.rs
- algonaut_transaction/src/tx_group.rs
- src/algod/mod.rs
- src/algod/v1/mod.rs
- src/algod/v2/mod.rs
- src/error.rs
- src/indexer/mod.rs
- src/indexer/v2/mod.rs
- src/kmd/mod.rs
- src/kmd/v1/mod.rs
- src/lib.rs
Closes https://github.com/manuelmauro/algonaut/issues/44
> Refactor errors

- algonaut_transaction/src/builder.rs
Also removed `txn_type` fn as it conflicts with convenience.
> Add missing convenience to txn builder

- README.md
- algonaut_core/src/lib.rs
- algonaut_transaction/src/account.rs
- algonaut_transaction/src/api_model.rs
- algonaut_transaction/src/builder.rs
- algonaut_transaction/src/lib.rs
- algonaut_transaction/src/transaction.rs
- examples/asset_clawback.rs
- examples/asset_create.rs
- examples/asset_optin.rs
- examples/asset_transfer.rs
- examples/key_reg.rs
- examples/kmd_sign_submit_transaction.rs
- examples/sign_offline.rs
- src/algod/v2/mod.rs
- tests/test_trasactions.rs
Mainly related to transaction building.
Closes https://github.com/manuelmauro/algonaut/issues/49, https://github.com/manuelmauro/algonaut/issues/32
> Diverse refactorings

- algonaut_core/src/address.rs
> chore(algonaut_core::address): fix comment typo

- algonaut_core/src/address.rs
- algonaut_crypto/src/lib.rs
- algonaut_encoding/src/lib.rs
- algonaut_model/Cargo.toml
- algonaut_model/src/algod/v2/mod.rs
- algonaut_transaction/src/api_model.rs
Just noticed that this breaks the deserialization of the signed [My Algo](https://github.com/randlabs/myalgo-connect) blob. Since the current solution is workaround-ish (see https://github.com/manuelmauro/algonaut/issues/84) I'm reverting for now. I opened an issue to address this in 0.4 https://github.com/manuelmauro/algonaut/issues/86
> Revert "Complete deserialization of pending transaction"

- algonaut_core/src/address.rs
- tests/test_account.rs
See https://github.com/manuelmauro/algonaut/pull/87#issue-700521518
> Revert "Disable ported tests involving deserialization of local txs"

- Cargo.toml
- algonaut_client/Cargo.toml
- algonaut_transaction/Cargo.toml
(with help from https://github.com/est31/cargo-udeps)
> deps: remove unused dependencies

- algonaut_core/src/address.rs
- algonaut_model/Cargo.toml
- algonaut_model/src/algod/v2/mod.rs
Closes https://github.com/manuelmauro/algonaut/issues/101
> Deserialize strings to Address (algod)

- src/error.rs
For #126.
Added a few more methods (that are private) which may or may not be helpful in the future.
> Add series of functions for "simpler" error checking.

- algonaut_transaction/src/tx_group.rs
- examples/atomic_swap.rs
Closes https://github.com/manuelmauro/algonaut/issues/136
> Replace vector with mut slice in assign_group_id

- algonaut_transaction/src/account.rs
- algonaut_transaction/src/builder.rs
- algonaut_transaction/src/transaction.rs
- examples/app_call.rs
- examples/app_clear_state.rs
- examples/app_close_out.rs
- examples/app_create.rs
- examples/app_delete.rs
- examples/app_optin.rs
- examples/app_update.rs
- examples/asset_clawback.rs
- examples/asset_create.rs
- examples/asset_optin.rs
- examples/asset_transfer.rs
- examples/atomic_swap.rs
- examples/key_reg.rs
- examples/payment.rs
- examples/sign_offline.rs
- tests/step_defs/integration/applications.rs
- tests/test_account.rs
- tests/test_transactions.rs
> Change input of sign_transaction to be an actual Transaction.

- algonaut_crypto/src/lib.rs
- algonaut_model/src/indexer/v2/mod.rs
Closes https://github.com/manuelmauro/algonaut/issues/138
> Fix deserialization bugs

- algonaut_core/src/lib.rs
Closes https://github.com/manuelmauro/algonaut/issues/135
> Remove MicroAlgos/Algos conversions

- algonaut_transaction/src/builder.rs
- algonaut_transaction/src/transaction.rs
Fixes https://github.com/manuelmauro/algonaut/issues/146
> Use hardcoded estimated tx size, improve naming

- algonaut_abi/src/abi_encode.rs
- algonaut_abi/src/abi_encode_test.rs
- algonaut_abi/src/abi_interactions.rs
- algonaut_transaction/src/builder.rs
- examples/app_call.rs
- tests/step_defs/integration/applications.rs
Added by mistake - this builder is specific for `NoOp`.
> Remove app call parameter

- algonaut_model/src/indexer/v2/mod.rs
Just some updates I needed. The proper fix is https://github.com/manuelmauro/algonaut/issues/164 / https://github.com/manuelmauro/algonaut/issues/165
> Indexer updates

- algonaut_model/src/indexer/v2/mod.rs
Admittedly I don't know what the types do exactly, so I didn't feel right trying to leave comments. The documentation could be better
> Add stateproof transaction support to v2 indexer

- .gitignore
- algonaut_client/src/algod/v2/mod.rs
- algonaut_client/src/indexer/v2/mod.rs
- algonaut_client/src/kmd/v1/mod.rs
- src/algod/v2/mod.rs
- src/indexer/v2/mod.rs
- src/kmd/v1/mod.rs
> Derive Clone on clients

- algonaut_model/src/indexer/v2/mod.rs
https://github.com/manuelmauro/algonaut/issues/204
> search txid using txid
