manuelmauro/algonaut

algonaut_client/src/algod/v1/mod.rs, algonaut_client/src/algod/v2/mod.rs, algonaut_client/src/error.rs, algonaut_client/src/extensions/mod.rs, algonaut_client/src/extensions/reqwest.rs, algonaut_client/src/indexer/v2/mod.rs, algonaut_client/src/kmd/v1/mod.rs, algonaut_client/src/lib.rs
The api messages now show in `AlgorandError`: 
Debug:
> Err(HttpError(HttpError { message: "failed to parse the address", reqwest_error: reqwest::Error { kind: Status(400), url: Url { scheme: "http", username: "", password: None, host: Some(Domain("localhost")), port: Some(4001), path: "/v2/accounts/a", query: None, fragment: None } } }))
Display:
> http error: failed to parse the address, HTTP status client error (400 Bad Request) for url (http://localhost:4001/v2/accounts/a)
Basically, `reqwest::Error` is mapped to `HttpError`, which contains the error and a message. If the api doesn't return any message, or it's not a http status error, message is an empty string.
Closes #5
=> Improve error messages from API calls #5

algonaut_client/Cargo.toml, algonaut_client/tests/test_trasactions.rs, algonaut_core/src/lib.rs, algonaut_transaction/src/account.rs, algonaut_transaction/src/transaction.rs
=> Support logic signatures

algonaut_client/src/algod/v1/mod.rs, algonaut_client/src/kmd/v1/mod.rs, algonaut_client/tests/test_trasactions.rs, algonaut_core/Cargo.toml, algonaut_core/src/lib.rs, algonaut_transaction/src/account.rs, algonaut_transaction/src/api_transaction.rs, algonaut_transaction/src/auction.rs, algonaut_transaction/src/builder.rs, algonaut_transaction/src/lib.rs, algonaut_transaction/src/transaction.rs, examples/sign_offline.rs
Closes https://github.com/manuelmauro/algonaut/issues/29
Removed too some ambiguity with optional values, if fields are not set it's always `None`, independently of the type. Removed the `Deserialize` implementation, as we're not using it yet. When we add `Deserialize` we don't have to add the `default` serde attribute again, because it works automatically for `Option`.
=> Create dedicated api transaction and fix serialization

algonaut_client/src/algod/v1/message.rs, algonaut_client/src/indexer/v2/message.rs, examples/query.rs
`Query*` struct fields are all optional, setting them all to `None` is how you'd represent a request to an endpoint without queries like `http://$INDEXER_URL/accounts`.
Methods like this require a `Query*` struct even if the structs fields are entirely `None`:
https://github.com/manuelmauro/algonaut/blob/8a3526390de4d5f9a79e399b0c8b8f2e2d0d6f01/algonaut_client/src/indexer/v2/mod.rs#L30
This commit derives the `Default` trait for all `Query*` structs which provides a convenient way of constructing queries without needing to write out the entire struct body simply to set values to `None` manually:
```rust
// query Account using default query parameters (all None).
let accounts = indexer.accounts(&QueryAccount::default())?.accounts;
// query Applications with custom query parameters.
let mut …
```
=> derive Default for all Query* structs

algonaut_transaction/src/account.rs
I noticed that the transaction ids here don't match the ones generated in the Java SDK. It seems that we've to hash the bytes used to generate the signature and not the signature. See [Java](https://github.com/algorand/java-algorand-sdk/blob/34b27834770e8cc18240b78589f8d7c7ebce215f/src/main/java/com/algorand/algosdk/transaction/Transaction.java#L1230) and [Go](https://github.com/algorand/go-algorand-sdk/blob/adb6d4be485483d4b95d5eb7742943dc2f2109e9/crypto/crypto.go#L140)
=> Fix incorrect transaction ids

algonaut_core/src/lib.rs, algonaut_crypto/src/lib.rs
The current debug representation shows everywhere byte arrays and that makes it difficult to work with and compare with goal and other SDKs. With this PR hashes are displayed as base32 encoded strings and the signature as base64:
```
SignedTransaction {
sig: Some(
RQOF4OazISb9AMUtcr4A1F/mpph+JeLQVCGiCQymSeRxWukKzNZuSgJzMDRPixlswhHseXOuvgt8FJN2DGkGDQ==,
),
multisig: None,
logicsig: None,
transaction: Transaction {
fee: MicroAlgos(
10000,
),
first_valid: Round(
9025,
),
genesis_hash: 2YKA7K2Z5JDSTNMWHEC65NVL7UEL5TDUHFZQMLCBHWLYXPGSLQOA,
last_valid: Round(
9035,
),
sender: GIZTTA56FAJNAN7ACK3T6YG34FH32ETDULBZ6ENC4UV7EEHPXJGGSPCMVU,
txn_type: Payment(
Payment {
receiver: BFRTECKTOOE7A5LHCF3TTEOH2A7BW46IYT2SX5VP6ANKEXHZYJY77SJTVM,
amount: MicroAlgos(
123456,
),
close_remainder_to: None,
},
), …
```
=> Improve debug representation of transactions

algonaut_client/src/algod/v2/message.rs, algonaut_client/src/algod/v2/mod.rs, algonaut_client/tests/test_trasactions.rs, algonaut_core/src/lib.rs, algonaut_transaction/src/account.rs, algonaut_transaction/src/api_transaction.rs, algonaut_transaction/src/transaction.rs, algonaut_transaction/src/tx_group.rs, examples/sign_offline.rs
- Use enums for transaction and logic signature types, separate api from domain objects.
- Refactor signing of transactions and logic in `Account`. Removed `merge_multisig_transactions`, which is not needed anymore. Minimized scope of some public functions, to be able to compose more cleanly on the caller side.
- Created a couple of newtypes and convenience functions
- Renamed some public functions, like `sign_transaction_msig` in `init_transaction_msig` to make clearer what they do (in this case generate a new msig). This one is rather tentative, can revert if it causes too much inconvenience with the official SDKs.
Closes https://github.com/manuelmauro/algonaut/issues/28
=> Account and signing refactoring

algonaut_transaction/src/api_model.rs, examples/new_asa_sandnet.rs
- Some issues I found when signing directly (which for some reason is more restrictive than KMD).
- Retrieval of created asset id (used in the [docs](https://developer.algorand.org/docs/features/asa/#creating-an-asset), ported from the [Java SDK](https://github.com/algorand/java-algorand-sdk/blob/e9871a544ad6155df8cb67f5d95ea38254f8a6a7/src/test/java/com/algorand/algosdk/cucumber/shared/Utils.java)). I modified it to return the pending transaction. Probably this function should be moved somewhere else but not sure where: In the Java SDK it's in a testing package. Docs suggest it's for public use. Maybe it should be in the root project. For now it's used only in this example so letting it there.
=> Create asset fixes, retrieve asset id

algonaut_transaction/src/api_model.rs, algonaut_transaction/src/builder.rs, algonaut_transaction/src/transaction.rs, examples/transfer_asa.rs
Some incorrectly assigned fields, `asset_close_to` [is optional](https://developer.algorand.org/docs/reference/transactions/#asset-transfer-transaction), removed `sender` from the transaction type as it's the same sender of the transaction. `sender` can be different if it's a clawback transaction but there's a different type for that.
=> Fix asset transfer

algonaut_transaction/src/api_model.rs, algonaut_transaction/src/builder.rs, algonaut_transaction/src/transaction.rs, examples/optin_asa.rs
Removed `asnd` (it has to be removed from the [documentation](https://developer.algorand.org/docs/reference/transactions/#asset-accept-transaction) too, it's only used for clawback). Renamed the remaining field to improve semantics.
=> Fix asset opt-in

algonaut_transaction/src/api_model.rs, algonaut_transaction/src/builder.rs, algonaut_transaction/src/transaction.rs
As per [docs](https://developer.algorand.org/docs/reference/transactions/#key-registration-transaction) the fields are required only online key registrations. Probably we should create different domain models for online/offline/toggle rewards. For now just fixing the api.
=> Make key registration transaction fields optional

algonaut_transaction/Cargo.toml
serde_bytes 0.11.4 adds support for bytes inside of Option, which `algonaut_transaction::api_model::ApiTransaction` depends on.
* https://github.com/serde-rs/bytes/releases/tag/0.11.4
=> deps(algonaut_transaction): bump serde_bytes 0.11 → 0.11.4

algonaut_client/src/algod/v2/mod.rs, algonaut_core/src/lib.rs, algonaut_model/src/algod/v2/mod.rs, algonaut_transaction/Cargo.toml, algonaut_transaction/src/account.rs, algonaut_transaction/src/api_model.rs, algonaut_transaction/src/builder.rs, algonaut_transaction/src/transaction.rs, examples/logic_sig_contract_account.rs, src/algod/v2/mod.rs, tests/test_account.rs, tests/test_logic_signature.rs
Improved the modeling around these types, e.g. before the trait to sign as a contract account could be implemented by any "compiled teal", which is not ideal semantically. Having a dedicated type for contract accounts is cleaner. Also, now only these contract accounts expose the hash as an address.
=> Improve CompiledTeal and contract account signing API

Cargo.toml, algonaut_client/Cargo.toml, src/algod/mod.rs, src/indexer/mod.rs, src/kmd/mod.rs
A simple switch for allowing `reqwest` to compile with `rustls` instead of `native` which relies on `openssl`.
`openssl` is known to be a non-trivial dependency in the compilation process.
=> Add feature flags for selecting rustls or openssl as the tls implementation.

algonaut_client/src/algod/v1/mod.rs, src/algod/mod.rs, src/indexer/mod.rs, src/kmd/mod.rs
It's useful for interfacing with third party services (e.g. [PureStake](purestake.io)) if they don't require a completely different API and instead just an API key.
There were a few methods earlier related to custom headers, whose values were largely ignored. Not entirely sure why this was the case, but went ahead and wired the pieces together.
The API is a little inconsistent (`headers` vs `header`) but wasn't sure if there was a reason for going with one or the other or if I should have implemented both.
=> Add ability to include additional custom headers.

algonaut_core/src/lib.rs
Useful, for example when you want to treat SuggestedTransactionParams like a JSON object.
=> Derive Serialize, Deserialize for SuggestedTransactionParams

algonaut_model/src/indexer/v2/mod.rs
1. use `deserialize-hash` for genesis transaction - same as `Block`
2. make signature field optional
When using `Indexer::account_transactions`
Without fix 1. `Error: http error: None, Client error: error decoding response body: Invalid byte array length: 44 at line 1 column 234`
Without fix 2. `Error: http error: None, Client error: error decoding response body: missing field 'signature' at line 1 column 6690`
=> Fixes for Indexer AccountTransactions deserialisation

algonaut_client/src/algod/v2/mod.rs, algonaut_core/src/lib.rs, algonaut_encoding/src/lib.rs, algonaut_model/src/algod/v2/mod.rs, algonaut_transaction/src/account.rs, algonaut_transaction/src/api_model.rs, algonaut_transaction/src/builder.rs, algonaut_transaction/src/contract_account.rs, algonaut_transaction/src/lib.rs, algonaut_transaction/src/transaction.rs, examples/app_create.rs, examples/app_update.rs, examples/logic_sig_contract_account.rs, examples/logic_sig_delegated.rs, examples/logic_sig_delegated_multi.rs, src/algod/v2/mod.rs, src/error.rs, tests/step_defs/integration/applications.rs, tests/test_account.rs, tests/test_logic_signature.rs, tests/test_trasactions.rs
The compiled TEAL hash is now generated by the SDK. We can't assume the hash to always be pre-generated, e.g. when loading the compiled programs from a database (where it would be wasteful to store the hash). Supporting both the pre-generated hash and the on-demand hash seemed overkill (we have `ContractAccount` to cache the address, which is likely the most frequent use of this hash) so for now it's always generated by the SDK. This change also allowed a refactoring which simplified the functionality around `CompiledTeal` significantly.
=> Generate program hash clientside and CompiledTeal refactoring

examples/app_call.rs, examples/app_clear_state.rs, examples/app_close_out.rs, examples/app_create.rs, examples/app_delete.rs, examples/app_optin.rs, examples/app_update.rs, examples/asset_clawback.rs, examples/asset_create.rs, examples/asset_optin.rs, examples/asset_transfer.rs, examples/atomic_swap.rs, examples/indexer_query.rs, examples/key_reg.rs, examples/logic_sig_contract_account.rs, examples/logic_sig_delegated.rs, examples/logic_sig_delegated_multi.rs, examples/multi_sig.rs, examples/payment.rs
This lets the example code imports work when copied and pasted to external projects that depend only on the "algonaut" crate, rather than the individual crates.
=> refactor(examples): update imports to use "algonaut::" namespace

algonaut_transaction/src/api_model.rs
Added check for tx sender == asset receiver to identify the tx as opt-in
=> Fix 0 amount asset transfer deserialized to asset opt-in

algonaut_model/src/indexer/v2/mod.rs
`Option<Vec>` is not meaningful here and it makes accessing the field inconvenient. 
When the API doesn't send the value (which means empty vector anyway, due to the API's zero values policy), it will be converted into an empty vector.
Also fixes the deserialization of `ApplicationLocalState.key_value`, which is was incorrectly non-optional.
Added `skip_serializing_if` too, though it's not strictly needed, see https://github.com/manuelmauro/algonaut/pull/130
=> Replace Option<Vec> with <Vec> + default deserialization

algonaut_core/src/lib.rs, algonaut_model/src/algod/v2/mod.rs, algonaut_transaction/src/builder.rs, algonaut_transaction/src/transaction.rs, examples/app_call.rs, examples/app_clear_state.rs, examples/app_close_out.rs, examples/app_create.rs, examples/app_delete.rs, examples/app_optin.rs, examples/app_update.rs, examples/asset_clawback.rs, examples/asset_create.rs, examples/asset_optin.rs, examples/asset_transfer.rs, examples/atomic_swap.rs, examples/key_reg.rs, examples/kmd_sign_submit_transaction.rs, examples/logic_sig_contract_account.rs, examples/logic_sig_delegated.rs, examples/logic_sig_delegated_multi.rs, examples/multi_sig.rs, examples/payment.rs, examples/sign_offline.rs, src/algod/v2/mod.rs, tests/step_defs/integration/applications.rs, tests/test_account.rs, tests/test_trasactions.rs
Basically ported this: https://github.com/algorand/go-algorand-sdk/blob/c37407700af350ef13aea10b844529144f498b6c/future/transaction.go#L14-L29
Notes:
- The semantics around the fee "estimation" are a bit weird, it's more an accurate prediction of the signed txn size, if it has a regular signature (not lsig or msig). But I didn't want to diverge much from the official SDK for now. 
- Renamed the `fee` field in the [txn params](https://developer.algorand.org/docs/rest-apis/algod/v2/#get-v2transactionsparams) into `fee_per_byte`, to make clearer what it is.
- Added an enum `TxnFee` to the txn builder, to be able to set the fee to either "estimated" (based on `fee_per_byte` / `min_fee` and the "estimated" txn size) or fixed, which is just setting directly the txn's fee.
- The `TxnBuilder` …
=> Set transaction fee correctly

algonaut_transaction/src/builder.rs, examples/app_call.rs, examples/app_clear_state.rs, examples/app_close_out.rs, examples/app_create.rs, examples/app_delete.rs, examples/app_optin.rs, examples/app_update.rs, examples/asset_clawback.rs, examples/asset_create.rs, examples/asset_optin.rs, examples/asset_transfer.rs, examples/atomic_swap.rs, examples/key_reg.rs, examples/kmd_sign_submit_transaction.rs, examples/logic_sig_contract_account.rs, examples/logic_sig_delegated.rs, examples/logic_sig_delegated_multi.rs, examples/multi_sig.rs, examples/payment.rs, examples/sign_offline.rs, tests/step_defs/integration/applications.rs, tests/test_trasactions.rs
This is better since params are often reused (e.g. when building transaction groups).
=> Pass params as reference

examples/app_create.rs, examples/asset_create.rs, src/algod/v2/mod.rs, src/error.rs, src/indexer/v2/mod.rs, src/kmd/v1/mod.rs, tests/step_defs/util.rs
These errors are specific to the algod/kmd/indexer REST client wrappers and not general to Algonaut.
`ServiceError` sounds extraneous, as we don't have anything called "service", but it's a kind of implied name for the algod/kmd/indexer wrappers, which are currently in the root package. Moving these wrappers to a new package seems overkill. Another name could be "client wrapper" or something like that, but "service" sounds better.
Closes https://github.com/manuelmauro/algonaut/issues/99
=> Rename AlgonautError in ServiceError

Cargo.toml, README.md, algonaut_abi/Cargo.toml, algonaut_abi/README.md, algonaut_abi/src/abi_encode.rs, algonaut_abi/src/abi_encode_test.rs, algonaut_abi/src/abi_error.rs, algonaut_abi/src/abi_interaction_tests.rs, algonaut_abi/src/abi_interactions.rs, algonaut_abi/src/abi_json_tests.rs, algonaut_abi/src/abi_type.rs, algonaut_abi/src/abi_type_test.rs, algonaut_abi/src/biguint_ext.rs, algonaut_abi/src/lib.rs, algonaut_core/src/lib.rs, algonaut_transaction/src/api_model.rs, src/error.rs, src/lib.rs
Ported from the current last versions of the official SDKs (Go v1.14.1 and the unit tests mostly from Java 1.13.0, since I had issues running the Go tests. Go is supposed to be reference SDK - from what I could see, the tests were ported to the Java SDK, and there were some additional ones which I ported too).
Closes https://github.com/manuelmauro/algonaut/issues/149
=> Support ABI

algonaut_client/src/algod/v2/mod.rs, algonaut_core/src/lib.rs, algonaut_model/src/algod/v2/mod.rs, algonaut_model/src/lib.rs, algonaut_model/src/transaction.rs, algonaut_transaction/src/api_model.rs, algonaut_transaction/src/contract_account.rs, algonaut_transaction/src/lib.rs, algonaut_transaction/src/transaction.rs, examples/logic_sig_delegated.rs, examples/logic_sig_delegated_multi.rs, src/algod/v2/mod.rs, src/atomic_transaction_composer/mod.rs, tests/test_account.rs, tests/test_logic_signature.rs
Had to move some models around to be able to reference `ApiSignedTransaction` (previously in the transactions package) from `DryrunRequest` (which makes sense to keeps in the models package).
Further, nothing was working, changed the request format to msg pack, fixed deserialization etc.
=> Fix dryrun endpoint

algonaut_core/src/address.rs, src/lib.rs, src/util/dryrun_printer.rs, src/util/mod.rs
Ported: https://github.com/algorand/py-algorand-sdk/pull/283
Example call:
```rust
let req = create_dryrun(algod, &signed_txs).await?;
let res = algod.dryrun_teal(&req).await?;
for tx in res.txns {
println!("{}", app_trace(&tx)?);
}
```
Output:
Added new settings to specify individual columns width and display byte values as addresses.
=> Dryrun printer utility

algonaut_model/src/indexer/v2/mod.rs
Bug using the indexer to parse transactions if the tx type was ever asset freeze. Simple fix
s/axfrz/afrz
=> Rename axfrz to afrz

algonaut_model/src/transaction.rs, algonaut_transaction/src/api_model.rs, algonaut_transaction/src/builder.rs, algonaut_transaction/src/transaction.rs, src/atomic_transaction_composer/mod.rs, src/util/dryrun_printer.rs, tests/step_defs/integration/abi.rs
This adds box storage support for creating and signing transactions and addresses issue #191.
=> Add box storage support for transaction signing

algonaut_algod/src/models/asset_params.rs
When it deserializes `models::Asset` from an API call like `let asset = client.asset(1903271236).await?;
` and when `metadata_hash` is missed there is an error of `Error: Msg: Serde(Error("missing field `metadata-hash`", line: 1, column: 312))`
the little fix of adding `#[serde(default)]` to the field attribute fixes this issue
=> Fix asset deserialization of metadata_hash field when it is missed
